version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ra-postgres
    environment:
      POSTGRES_DB: ra_platform
      POSTGRES_USER: ra_user
      POSTGRES_PASSWORD: ra_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ra-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ra-backend
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ra_platform
      DB_USER: ra_user
      DB_PASSWORD: ra_password
      JWT_SECRET: ra_jwt_secret_2024
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - ra-network
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ra-frontend
    environment:
      REACT_APP_API_URL: http://localhost:3001/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - ra-network
    command: npm start

volumes:
  postgres_data:

networks:
  ra-network:
    driver: bridge